# Generated by Django 5.1.2 on 2024-10-16 12:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='color',
            field=models.SmallIntegerField(blank=True, default=api.models.random_section_color),
        ),
    ]
